### ISSUE TITLE
Can't create account/login

### ISSUE THREAD

**Issue by BramDriesen** [Usecue/InvoiceLion#3]
I wanted to t'est InvoiceLion yesterday but I can't get past the login screen. When creating a account in the new db I get this error.

> Fatal error: Uncaught MintyPHP\DBError: Unknown column 'currency_id' in 'field list' in /app/vendor/mintyphp/core/src/DB.php:34 Stack trace: #0 /app/vendor/mintyphp/core/src/DB.php(84): MintyPHP\DB::error('Unknown column ...') #1 [internal function]: MintyPHP\DB::queryTyped('SELECT `currenc...', '1') #2 /app/vendor/mintyphp/core/src/DB.php(42): forward_static_call_array('DB::queryTyped', Array) #3 [internal function]: MintyPHP\DB::query('SELECT `currenc...', '1') #4 /app/vendor/mintyphp/core/src/DB.php(168): forward_static_call_array('DB::query', Array) #5 /app/pages/auth/register().php(27): MintyPHP\DB::selectValue('SELECT `currenc...', '1') #6 /app/web/index.php(50): require('/app/pages/auth...') #7 {main} thrown in /app/vendor/mintyphp/core/src/DB.php on line 34

Could it be that the database script is outdated?

**Comment by mevdschee** [comment]
>Could it be that the database script is outdated?

I updated it, can you let me know whether or not that helped?

**Comment by ikswokjam** [comment]
It helped! thanks for the quick reply
