### ISSUE TITLE
nginx+mariadb+php Stack - Error 404

### ISSUE THREAD

**Issue by mr2017x** [usecue/invoicelion#7]
Hello,

i face issues with setting up the page. installed everything, composed, installed database, linked (vendor and config) to root dir, but still it runs into nirvana...

domain/auth/login?url= blank page 404...? do you have some hints or further logging options?

thanks in advance

**Comment by mevdschee** [comment]
Hi, try it with Apache and mod_php first, because the FPM route is a but harder to set up correctly.

In case you want to continue the FPM route, then read this:

https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/

**Comment by mr2017x** [comment]
Hi Maurits,

thank for your help:

1. fpm with php (7.4.16) is running
2. fascgi_param is done
3. test.php with phpinfo() is running smooth, fine and fast
4. website root is done to web/
5. ok, got it


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
has to be placed in server config.

but:
6. which user for 1. login?
Thanks in advance

**Comment by mevdschee** [comment]
Use url `/auth/register` to create one.

**Comment by mr2017x** [comment]
> Hi,
> 
> Wow.. very good that you got this running.. I'm impressed!
> 
> > 1. which user for 1. login?
> 
> Use url `/auth/register` to create one.
> 
> Enjoy the software and feel free to open another issue!
> 
> Kind regards, Maurits

hi, auth register isn't working - 404 i see that it writes something to db but i cannot reengineer the password :-D (damn this day is nothing for me)

**Comment by mevdschee** [comment]
if you register the software sends

**Comment by mr2017x** [comment]
> > hi, auth register isn't working - 404
> 
> If you register the software sends an email to verify your email address before you can set your password. Probably the mailer on your machine is not working.
> 
> > damn this day is nothing for me
> 
> Don't be hard on yourself, this project is not documented at all. Thank you for your patience!
> 
> Kind regards, Maurits

Hi Maurits,

seems so...

Mailer works for other stuff, but i cannot find configuration of invoicelion for mailing etc? 

So progress is: i register - mail gets out - i click on it - i set pw?

ok, but still, the https://www.invoicelion.com/auth/login?url= doesn't work neither...

**Comment by ikswokjam** [comment]
Also needed to change the PHP.ini, cgi.fix_pathinfo was set to 0 needed to be one for 
fastcgi_param   PATH_TRANSLATED     $document_root$fastcgi_path_info; to function. 

I never changed it but still it was 0 although the default is 0  

Still hanging on 6. how and where to set the mailer/smtp settings.

**Comment by paulcrown** [comment]
@ikswokjam I installed and configured sendmail in /etc/mail directory on Ubuntu Server.  InvoiceLion uses sendmail MTA.

**Comment by mevdschee** [comment]
@paulcrown thank you, you are 100% correct, it uses the PHP configured SMTP, which is sendmail by default.

**Comment by ikswokjam** [comment]
@paulcrown @mevdschee Thank you! Sendmail worked for me.
